name: PR Workflow

on:
  - pull_request

jobs:
  pr-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "this pr workflow"
      - name: Checkout repository
        # To reference external workflows, we use the `uses` keyword.
        # The thing after the `@` is the version of the workflow, and
        # references a Git tag.
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build